name: Build and Publish NuGet Package

on:
  push:
    tags:
      - "v*" # Only triggers when a version tag (e.g., v1.0.0) is pushed

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x" # Use a single version for publishing

      - name: Restore dependencies
        run: dotnet restore NepDate.sln

      - name: Build
        run: dotnet build NepDate.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test NepDate.sln --configuration Release --no-build --verbosity normal

      - name: Pack
        run: dotnet pack src/NepDate/NepDate.csproj --configuration Release --no-build --output nupkgs

      - name: Extract Version from Tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Push to NuGet
        run: dotnet nuget push nupkgs/NepDate.${VERSION}.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
