name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: windows-latest # Changed to Windows

    strategy:
      matrix:
        configuration: [Debug, Release]
        # Use specific versions.  For .NET Core/5+, use A.B.x syntax to get the latest patch.
        framework: [
            net472, # .NET Framework 4.7.2
            7.0.x, # .NET 7.0 - gets latest patch
            9.0.x, # .NET 9.0 - gets latest patch
          ]

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.framework }} # Use matrix to specify .NET version

      - name: Restore dependencies
        run: dotnet restore NepDate.sln

      - name: Build
        run: |
          dotnet build NepDate.sln \
            --configuration ${{ matrix.configuration }} \
            --framework ${{ matrix.framework }} \
            --no-restore

      - name: Test
        run: |
          dotnet test NepDate.sln \
            --configuration ${{ matrix.configuration }} \
            --framework ${{ matrix.framework }} \
            --no-build --verbosity normal
